sudo: required
services:
  - docker

before_install:
  - docker build -t jaworekb/frontend -f Dockerfile.dev .

script:
  - docker run jaworekb/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-central-1-016182127253"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"